title: Break the Mold
author:
  name: Jozef Porubcin
  email: jporubci@nd.edu
description: >-
  Blog for CSE 40842 Hackers in the Bazaar.
baseurl: "/Hackers-in-the-Bazaar"
url: "https://jporubci.github.io"

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/jporubci" }
